-- Ejecuta este archivo completo en Supabase > SQL Editor.
-- Es seguro ejecutarlo más de una vez: no reinicia el stock existente.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text not null,
    display_name text,
    avatar_url text,
    role text not null default 'customer' check (role in ('customer', 'owner')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.services (
    id uuid primary key default gen_random_uuid(),
    slug text not null unique,
    name text not null,
    category text not null,
    description text not null,
    price numeric(10, 2) not null check (price > 0),
    stock integer not null default 0 check (stock >= 0),
    image_path text not null,
    active boolean not null default true,
    sort_order integer not null default 100,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.orders (
    id uuid primary key default gen_random_uuid(),
    receipt_number text not null unique,
    user_id uuid not null references auth.users(id) on delete restrict,
    customer_email text not null,
    total numeric(10, 2) not null check (total >= 0),
    appointment_at timestamptz not null,
    device_model text not null,
    phone text not null,
    notes text,
    payment_brand text not null,
    payment_last4 text not null check (payment_last4 ~ '^\d{4}$'),
    status text not null default 'scheduled' check (status in ('scheduled', 'confirmed', 'completed', 'cancelled')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
    id bigint generated by default as identity primary key,
    order_id uuid not null references public.orders(id) on delete cascade,
    service_id uuid references public.services(id) on delete set null,
    service_name text not null,
    unit_price numeric(10, 2) not null check (unit_price >= 0),
    quantity integer not null check (quantity > 0),
    line_total numeric(10, 2) not null check (line_total >= 0)
);

create index if not exists orders_user_id_idx on public.orders(user_id);
create index if not exists orders_appointment_at_idx on public.orders(appointment_at);
create index if not exists order_items_order_id_idx on public.order_items(order_id);

alter table public.profiles enable row level security;
alter table public.services enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Public can read active services" on public.services;
create policy "Public can read active services"
on public.services for select
using (active = true);

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
on public.profiles for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Users can read own orders" on public.orders;
create policy "Users can read own orders"
on public.orders for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can read own order items" on public.order_items;
create policy "Users can read own order items"
on public.order_items for select
to authenticated
using (
    exists (
        select 1 from public.orders
        where orders.id = order_items.order_id
          and orders.user_id = auth.uid()
    )
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
    insert into public.profiles (id, email, display_name, avatar_url)
    values (
        new.id,
        coalesce(new.email, ''),
        coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', split_part(coalesce(new.email, ''), '@', 1)),
        coalesce(new.raw_user_meta_data ->> 'avatar_url', new.raw_user_meta_data ->> 'picture', '')
    )
    on conflict (id) do nothing;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.create_service_order(
    p_user_id uuid,
    p_customer_email text,
    p_items jsonb,
    p_appointment_at timestamptz,
    p_device_model text,
    p_phone text,
    p_notes text,
    p_payment_brand text,
    p_payment_last4 text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_item jsonb;
    v_service public.services%rowtype;
    v_service_id uuid;
    v_quantity integer;
    v_total numeric(10, 2) := 0;
    v_order_id uuid;
    v_receipt text;
    v_items jsonb;
begin
    if p_user_id is null or not exists (select 1 from auth.users where id = p_user_id) then
        raise exception 'Usuario no válido.';
    end if;

    if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 or jsonb_array_length(p_items) > 20 then
        raise exception 'El carrito no es válido.';
    end if;

    if p_appointment_at < now() + interval '1 hour' or p_appointment_at > now() + interval '180 days' then
        raise exception 'La fecha de la cita no es válida.';
    end if;

    for v_item in select value from jsonb_array_elements(p_items)
    loop
        v_service_id := (v_item ->> 'id')::uuid;
        v_quantity := (v_item ->> 'quantity')::integer;

        if v_quantity < 1 or v_quantity > 10 then
            raise exception 'La cantidad solicitada no es válida.';
        end if;

        select * into v_service
        from public.services
        where id = v_service_id and active = true
        for update;

        if not found then
            raise exception 'Uno de los servicios ya no está disponible.';
        end if;

        if v_service.stock < v_quantity then
            raise exception 'No hay suficiente stock para %.', v_service.name;
        end if;

        v_total := v_total + (v_service.price * v_quantity);
    end loop;

    v_receipt := 'RSF-' || to_char(clock_timestamp(), 'YYYYMMDD') || '-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6));

    insert into public.orders (
        receipt_number, user_id, customer_email, total, appointment_at,
        device_model, phone, notes, payment_brand, payment_last4
    ) values (
        v_receipt, p_user_id, p_customer_email, v_total, p_appointment_at,
        p_device_model, p_phone, nullif(p_notes, ''), p_payment_brand, p_payment_last4
    ) returning id into v_order_id;

    for v_item in select value from jsonb_array_elements(p_items)
    loop
        v_service_id := (v_item ->> 'id')::uuid;
        v_quantity := (v_item ->> 'quantity')::integer;

        select * into v_service from public.services where id = v_service_id;

        insert into public.order_items (
            order_id, service_id, service_name, unit_price, quantity, line_total
        ) values (
            v_order_id, v_service.id, v_service.name, v_service.price,
            v_quantity, v_service.price * v_quantity
        );

        update public.services
        set stock = stock - v_quantity, updated_at = now()
        where id = v_service.id;
    end loop;

    select coalesce(jsonb_agg(jsonb_build_object(
        'name', service_name,
        'unitPrice', unit_price,
        'quantity', quantity,
        'lineTotal', line_total
    ) order by id), '[]'::jsonb)
    into v_items
    from public.order_items
    where order_id = v_order_id;

    return jsonb_build_object(
        'id', v_order_id,
        'receiptNumber', v_receipt,
        'customerEmail', p_customer_email,
        'total', v_total,
        'appointmentAt', p_appointment_at,
        'deviceModel', p_device_model,
        'phone', p_phone,
        'status', 'scheduled',
        'paymentBrand', p_payment_brand,
        'paymentLast4', p_payment_last4,
        'createdAt', now(),
        'items', v_items
    );
end;
$$;

revoke all on function public.create_service_order(uuid, text, jsonb, timestamptz, text, text, text, text, text) from public;
grant execute on function public.create_service_order(uuid, text, jsonb, timestamptz, text, text, text, text, text) to service_role;

insert into public.services (id, slug, name, category, description, price, stock, image_path, active, sort_order)
values
    ('10000000-0000-4000-8000-000000000001', 'cambio-de-pantalla', 'Cambio de pantalla', 'Pantallas', 'Reemplazo de pantalla quebrada, manchada o con fallas táctiles. Incluye diagnóstico previo del display, touch y conexión interna.', 350, 3, '/img/servicio-pantalla.png', true, 1),
    ('10000000-0000-4000-8000-000000000002', 'cambio-de-bateria', 'Cambio de batería', 'Baterías', 'Sustitución segura de batería para recuperar duración, rendimiento y estabilidad de carga del dispositivo.', 488, 4, '/img/servicio-bateria.png', true, 2),
    ('10000000-0000-4000-8000-000000000003', 'puerto-de-carga', 'Puerto de carga', 'Puerto de carga', 'Limpieza, reparación o reemplazo del conector cuando el teléfono no carga, se desconecta o no reconoce el cable.', 150, 2, '/img/servicio-carga.png', true, 3),
    ('10000000-0000-4000-8000-000000000004', 'reparacion-de-camara', 'Reparación de cámara', 'Cámaras', 'Diagnóstico y solución para fallas de enfoque, imagen borrosa, cámara negra o daños en el módulo frontal o trasero.', 420, 2, '/img/servicio-camara.png', true, 4),
    ('10000000-0000-4000-8000-000000000005', 'reparacion-de-audio', 'Reparación de audio', 'Audio', 'Revisión y reparación de bocinas, micrófono y auricular para llamadas y reproducción de sonido claras.', 260, 5, '/img/servicio-audio.png', true, 5),
    ('10000000-0000-4000-8000-000000000006', 'software-y-desbloqueo', 'Software y desbloqueo', 'Software', 'Actualización, restauración y optimización para corregir lentitud, errores del sistema y aplicaciones inestables.', 180, 6, '/img/servicio-software.png', true, 6)
on conflict (id) do update set
    slug = excluded.slug,
    name = excluded.name,
    category = excluded.category,
    description = excluded.description,
    price = excluded.price,
    image_path = excluded.image_path,
    active = excluded.active,
    sort_order = excluded.sort_order,
    updated_at = now();

grant usage on schema public to anon, authenticated, service_role;
grant select on public.services to anon, authenticated;
grant select on public.profiles, public.orders, public.order_items to authenticated;
grant all privileges on table public.profiles, public.services, public.orders, public.order_items to service_role;
grant usage, select on all sequences in schema public to service_role;
